name: Sentiment Analysis

on:
  workflow_dispatch:
    inputs:
      sentence:
        description: 'Enter a sentence for sentiment analysis'
        required: true
        default: 'I love learning about AI!'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --quiet textblob
          python -m textblob.download_corpora

      - name: Run sentiment analysis
        run: |
          python -c "
import sys
from textblob import TextBlob
sentence = '${{ github.event.inputs.sentence }}'
blob = TextBlob(sentence)
polarity = blob.sentiment.polarity
subjectivity = blob.sentiment.subjectivity
if polarity > 0:
    sentiment = 'Positive'
elif polarity < 0:
    sentiment = 'Negative'
else:
    sentiment = 'Neutral'
print(f'Sentence: {sentence}')
print(f'Sentiment: {sentiment}')
print(f'Polarity: {polarity:.2f}, Subjectivity: {subjectivity:.2f}')
"
